---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: bggappv1-deploy
   labels:
      app: bgg
      tier: backend
      version: v1
spec:
   replicas: 2
   selector:
      matchLabels: 
         app: bgg
         tier: backend
         version: v1
   minReadySeconds: 5
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
   template:
      metadata:
         name: bggappv1-pod
         labels:
            app: bgg
            tier: backend
            version: v1
      spec:
         containers:
         - name: bggapp-container
           image: stackupiss/bgg-backend:v1
           args: 
           - --prefix
           - /v1
           envFrom:
           - configMapRef:
              name: bgg-cm
           - secretRef:
              name: bgg-secret
           ports:
           - containerPort: 3000
           livenessProbe:
              httpGet:
                 path: /v1/healthz
                 port: 3000
           resources:
               requests:
                  cpu: 50m 
                  memory: 96Mi
               limits:
                  cpu: 100m
                  memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
   name: bggappv1-svc
   labels:
      app: bgg
      tier: backend
      version: v1
spec:
   type: ClusterIP
   selector:
      app: bgg
      tier: backend
      version: v1
   ports:
   - port: 8080
     targetPort: 3000

--- 
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
   name: bggappv1-hpa
   labels:
      app: bgg
      tier: backend
      version: v1
spec:
   minReplicas: 1
   maxReplicas: 4
   scaleTargetRef:
      apiVersion: apps/v1 
      kind: Deployment 
      name: bggappv1-deploy
   metrics:
   - type: Resource 
     resource: 
         name: memory 
         target: 
            type: Utilization
            averageUtilization: 70
   - type: Resource 
     resource: 
         name: cpu 
         target: 
            type: Utilization
            averageUtilization: 80
