---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: bggdb-pvc
   labels:
      app: bgg
      tier: persistence
spec:
   storageClassName: do-block-storage
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
