---
apiVersion: v1
kind: ConfigMap
metadata:
   name: bgg-cm
   labels:
      app: bgg
data:
   BGG_DB_USER: root
   BGG_DB_PORT: "3306"
   BGG_DB_HOST: bggdb-svc.bggns.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
   name: bgg-secret
   labels:
      app: bgg

type: Opaque
data:
   BGG_DB_PASSWORD: Y2hhbmdlaXQ=
