---
apiVersion: v1
kind: Secret
metadata:
   name: wp-secret
   labels:
      name: wp-secret
data:
   # wordpress
   ROOT_PASSWORD: d29yZHByZXNz
   WORDPRESS_DB_PASSWORD: d29yZHByZXNz

---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wp-cm
   labels:
      name: wp-cm
data:
   WORDPRESS_DB_HOST: wpdb-cluster-mysql-master
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_NAME: wpdb

